src/RSS.CompleteApp/ViewModels/SupplierViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace RSS.CompleteApp.ViewModels
{
    public class SupplierViewModel
    {
        [Key]
        public Guid Id { get; set; }

        [DisplayName("Nome")]
        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        [StringLength(100, ErrorMessage = "o campo {0} precisa ter entre {2} e {1}", MinimumLength = 2)]
        public string Name { get; set; }

        [DisplayName("Documento Identificação")]
        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        [StringLength(14, ErrorMessage = "o campo {0} precisa ter entre {2} e {1}", MinimumLength = 11)]
        public string IdentificationDocument { get; set; }

        [DisplayName("Tipo")]
        public int SupplierType { get; set; }

        [DisplayName("Ativo?")]
        public bool Active { get; set; }

        /*EF Relations*/
        public AddressViewModel Address { get; set; }
        public IEnumerable<ProductViewModel> Products { get; set; }
    }
}

src/RSS.CompleteApp/Controllers/SupplierController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using AutoMapper;
using KissLog;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RSS.Business.Interfaces;
using RSS.Business.Models;
using RSS.CompleteApp.Extensions;
using RSS.CompleteApp.ViewModels;

namespace RSS.CompleteApp.Controllers
{
    [Authorize]
    public class SupplierController : BaseController
    {
        //Deixamos o repositório injetado para agilizar buscas sem validações
        private readonly ISupplierRepository _supplierRepository;
        private readonly ISupplierService _supplierService;
        private readonly IMapper _mapper;
        private readonly ILogger _logger;

        public SupplierController(ISupplierRepository supplierRepository, 
                                    ISupplierService supplierService, 
                                    IMapper mapper,
                                    INotifiable notifiable,
                                    ILogger logger) : base(notifiable, logger)
        {
            _supplierRepository = supplierRepository;
            _supplierService = supplierService;
            _mapper = mapper;
        }

        [AllowAnonymous]
        [Route("lista-de-fornecedores")]
        public async Task<IActionResult> Index()
        {
            return View(_mapper.Map<IEnumerable<SupplierViewModel>>(await _supplierRepository.GetAll()));
        }

        [AllowAnonymous]
        [Route("dados-do-fornecedor/{id:guid}")]
        public async Task<IActionResult> Details(Guid id)
        {
            var supplierViewModel = await GetSupplierAddress(id);
            if (supplierViewModel == null)
            {
                return NotFound();
            }

            return View(supplierViewModel);
        }

        [ClaimsAuthorize("Supplier", "Add")]
        [Route("novo-fornecedor")]
        public IActionResult Create()
        {
            return View();
        }

        [ClaimsAuthorize("Supplier", "Add")]
        [Route("novo-fornecedor")]
        [HttpPost]
        public async Task<IActionResult> Create(SupplierViewModel supplierViewModel)
        {
            if (!ModelState.IsValid) return View(supplierViewModel);

            var supplier = _mapper.Map<Supplier>(supplierViewModel);

            await _supplierService.AddSupplier(supplier);

            if (!ValidOperation()) return View(supplierViewModel);

            TempData["Sucesso"] = "Fornecedor cadastrado com êxito";

            return RedirectToAction(nameof(Index));
        }

        [ClaimsAuthorize("Supplier", "Edit")]
        [Route("editar-cadastro-fornecedor/{id:guid}")]
        public async Task<IActionResult> Edit(Guid id)
        {
            var supplierViewModel = await GetSupplierProductsAddress(id);
            if (supplierViewModel == null)
            {
                return NotFound();
            }
            return View(supplierViewModel);
        }

        [ClaimsAuthorize("Supplier", "Edit")]
        [HttpPost]
        [Route("editar-cadastro-fornecedor/{id:guid}")]
        public async Task<IActionResult> Edit(Guid id, SupplierViewModel supplierViewModel)
        {
            if (id != supplierViewModel.Id) return NotFound();

            if(!ModelState.IsValid) return View(supplierViewModel);

            var supplier = _mapper.Map<Supplier>(supplierViewModel);
            await _supplierService.UpdateSupplier(supplier);

            if (!ValidOperation()) return View(await GetSupplierProductsAddress(id));

            TempData["Sucesso"] = "Cadastro atualizado com êxito";

            return RedirectToAction(nameof(Index));
        }

        [ClaimsAuthorize("Supplier", "Remove")]
        [Route("excluir-cadastro-fornecedor/{id:guid}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            var supplierViewModel = await GetSupplierAddress(id);
            if (supplierViewModel == null)
            {
                return NotFound();
            }

            return View(supplierViewModel);
        }

        [ClaimsAuthorize("Supplier", "Remove")]
        [HttpPost, ActionName("Delete")]
        [Route("excluir-cadastro-fornecedor/{id:guid}")]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var supplierViewModel = await GetSupplierAddress(id);

            if (supplierViewModel == null) return NotFound();

            await _supplierService.RemoveSupplier(id);

            if (!ValidOperation()) return View(supplierViewModel);

            TempData["Sucesso"] = "Fornecedor exclui com sucesso!";

            return RedirectToAction(nameof(Index));
        }

        [AllowAnonymous]
        [Route("endereco-fornecedor/{id:guid}")]
        public async Task<IActionResult> GetAddress(Guid id)
        {
            var supplier = await GetSupplierAddress(id);
            if (supplier == null) return NotFound();
            return PartialView("_AddressDetail", supplier);
        }

        [ClaimsAuthorize("Supplier", "Edit")]
        [Route("atualizar-endereco-fornecedor/{id:guid}")]
        public async Task<IActionResult> UpdateAddress(Guid id)
        {
            var supplier = await GetSupplierAddress(id);

            if (supplier == null) return NotFound();

            return PartialView("_UpdateAddress", new SupplierViewModel { Address = supplier.Address });
        }

        [ClaimsAuthorize("Supplier", "Edit")]
        [HttpPost]
        [Route("atualizar-endereco-fornecedor/{id:guid}")]
        public async Task<IActionResult> UpdateAddress(SupplierViewModel supplierViewModel)
        {
            ModelState.Remove("Name");
            ModelState.Remove("IdentificationDocument");

            if (!ModelState.IsValid) return PartialView("_UpdateAddress", supplierViewModel);

            await _supplierService.UpdateSupplierAddress(_mapper.Map<Address>(supplierViewModel.Address));

            if (!ValidOperation()) return PartialView("_UpdateAddress", supplierViewModel);

            var url = Url.Action("GetAddress", "Supplier", new { id = supplierViewModel.Address.SupplierId });

            return Json(new { success = true, url });
        }

        private async Task<SupplierViewModel> GetSupplierAddress(Guid id)
        {
            return _mapper.Map<SupplierViewModel>(await _supplierRepository.GetSupplierAddress(id));
        }

        private async Task<SupplierViewModel> GetSupplierProductsAddress(Guid id)
        {
            return _mapper.Map<SupplierViewModel>(await _supplierRepository.GetSupplierProductsAddress(id));
        }
    }
}

src/RSS.CompleteApp/Extensions/SummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using RSS.Business.Interfaces;
using System.Threading.Tasks;

namespace RSS.CompleteApp.Extensions
{
    public class SummaryViewComponent : ViewComponent
    {
        private readonly INotifiable _notifiable;

        public SummaryViewComponent(INotifiable notifiable)
        {
            _notifiable = notifiable;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var notification = await Task.FromResult(_notifiable.GetNotifications());

            notification.ForEach(n => ViewData.ModelState.AddModelError(string.Empty, n.Message));

            return View();
        }
    }
}

src/RSS.CompleteApp/Views/Supplier/Create.cshtml
@model RSS.CompleteApp.ViewModels.SupplierViewModel

@{
    ViewData["Title"] = "Novo Fornecedor";
}

<h1>@ViewData["Title"]</h1>
<hr />
<div class="row">
    <div class="col-md-10">
        <form asp-action="Create">
            <vc:summary></vc:summary>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdentificationDocument" class="control-label"></label>
                <input asp-for="IdentificationDocument" class="form-control" />
                <span asp-validation-for="IdentificationDocument" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SupplierType" class="control-label"></label> <br />
                <input type="radio" value="1" asp-for="SupplierType" checked />Pessoa Física <br />
                <input type="radio" value="2" asp-for="SupplierType"/>Pessoa Jurídica
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Active" /> @Html.DisplayNameFor(model => model.Active)
                </label>
            </div>
            <h4>Endereço</h4>
            <hr />
            <partial name="_Address"/>
            <div class="form-group">
                <input type="submit" value="Cadastrar" class="btn btn-primary" />
                <a class="btn btn-info" asp-action="Index">Voltar</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
        BuscaCep();
    </script>
}

src/RSS.CompleteApp/Views/Supplier/Delete.cshtml
@model RSS.CompleteApp.ViewModels.SupplierViewModel
@using RSS.CompleteApp.Extensions

@{
    ViewData["Title"] = "Excluir Fornecedor";
}

<h1>@ViewData["Title"]</h1>
<vc:summary></vc:summary>
<div>
    <h4>Esta ação será permanente!</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdentificationDocument)
        </dt>
        <dd class = "col-sm-10">
            @this.DocumentFormat(Model.SupplierType, Model.IdentificationDocument)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Active)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Active)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Excluir" class="btn btn-danger" />
        <a class="btn btn-info" asp-action="Index">Voltar</a>
    </form>
</div>

<partial name="_AddressDetail" />

src/RSS.CompleteApp/Views/Supplier/Details.cshtml
@model RSS.CompleteApp.ViewModels.SupplierViewModel
@using RSS.CompleteApp.Extensions 

@{
    ViewData["Title"] = "Detalhes";
}

<h1>@ViewData["Title"]</h1>

<div>
    <h4>Informação soemente leitura</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdentificationDocument)
        </dt>
        <dd class = "col-sm-10">
            @this.DocumentFormat(Model.SupplierType, Model.IdentificationDocument)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Active)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Active)
        </dd>
    </dl>
</div>

<div>
    <a class="btn btn-dark" asp-action="Edit" asp-route-id="@Model.Id">Editar</a>
    <a class="btn btn-info" asp-action="Index">Voltar</a>
</div>

<partial name="_AddressDetail" />

src/RSS.CompleteApp/Views/Supplier/Edit.cshtml
@model RSS.CompleteApp.ViewModels.SupplierViewModel

@{
    ViewData["Title"] = "Editar Fornecedor";
}

<h4>@ViewData["Title"]</h4>
<hr />
<form asp-action="Edit">
    <vc:summary></vc:summary>

    <input type="hidden" asp-for="Id" />

    <div class="form-row">
        <div class="form-group col-md-6">
            <label asp-for="Name" class="control-label"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
           
            <label asp-for="IdentificationDocument" class="control-label"></label>
            <input asp-for="IdentificationDocument" class="form-control" />
            <span asp-validation-for="IdentificationDocument" class="text-danger"></span>
        </div>
    


        <div class="form-group col-md-6">
            <label asp-for="SupplierType" class="control-label"></label>
            <div>
                <input type="radio" value="1" asp-for="SupplierType" checked="@(Model.SupplierType == 1)" />Pessoa Física <br />
                <input type="radio" value="2" asp-for="SupplierType" checked="@(Model.SupplierType == 2)"/>Pessoa Jurídica
            </div>
            <div>
                &nbsp;
            </div>
            <div class="form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Active" /> @Html.DisplayNameFor(model => model.Active)
                </label>
            </div>
        </div>
    </div>

    <div class="form-group">
        <input type="submit" value="Salvar" class="btn btn-primary" />
    </div>
</form>

<div id="TargetAddress">
    <partial name="_AddressDetail"/>
</div>
<hr />
<h4>Produtos</h4>
<div>
    <partial name="../Product/_ProductList" model="@Model.Products"/>
</div>

<div id="myModal" class="modal fade in">
    <div class="modal-dialog">
        <div class="modal-content">
            <div id="myModalContent"></div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
        $(document).ready(function () {
            AjaxModal();
        });
    </script>
}

src/RSS.CompleteApp/Views/Supplier/Index.cshtml
@using RSS.CompleteApp.Extensions 
@model IEnumerable<RSS.CompleteApp.ViewModels.SupplierViewModel>

@{
    ViewData["Title"] = "Lista de Fornecedores";
}

<h1>@ViewData["Title"]</h1>

<p>
    <a class="btn btn-info" asp-action="Create">Cadastrar Fornecedor</a>
</p>
<vc:summary></vc:summary>
<table class="table table-hover">
    <thead class="thead-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdentificationDocument)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Active)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @this.DocumentFormat(item.SupplierType, item.IdentificationDocument)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Active)
            </td>
            <td class="text-right">
                <a class="btn btn-info" asp-action="Details" asp-route-id="@item.Id"><span class="fa fa-search"></span></a>
                <a class="btn btn-warning" asp-action="Edit" asp-route-id="@item.Id"><span class="fa fa-pencil-alt"></span></a>
                <a class="btn btn-danger" supress-by-claim-name="Supplier" supress-by-claim-value="Remove" asp-action="Delete" asp-route-id="@item.Id"><span class="fa fa-trash"></span></a>
            </td>
        </tr>
}
    </tbody>
</table>

src/RSS.CompleteApp/Views/Supplier/_Address.cshtml
@model RSS.CompleteApp.ViewModels.SupplierViewModel


<div asp-validation-summary="ModelOnly" class="text-danger"></div>
<div class="form-group">
    <label asp-for="Address.Street" class="control-label"></label>
    <input asp-for="Address.Street" class="form-control" />
    <span asp-validation-for="Address.Street" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Address.Number" class="control-label"></label>
    <input asp-for="Address.Number" class="form-control" />
    <span asp-validation-for="Address.Number" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Address.Complement" class="control-label"></label>
    <input asp-for="Address.Complement" class="form-control" />
    <span asp-validation-for="Address.Complement" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Address.ZipCode" class="control-label"></label>
    <input asp-for="Address.ZipCode" class="form-control" />
    <span asp-validation-for="Address.ZipCode" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Address.Neighborhood" class="control-label"></label>
    <input asp-for="Address.Neighborhood" class="form-control" />
    <span asp-validation-for="Address.Neighborhood" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Address.City" class="control-label"></label>
    <input asp-for="Address.City" class="form-control" />
    <span asp-validation-for="Address.City" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Address.State" class="control-label"></label>
    <input asp-for="Address.State" class="form-control" />
    <span asp-validation-for="Address.State" class="text-danger"></span>
</div>

src/RSS.CompleteApp/Views/Supplier/_AddressDetail.cshtml
@model RSS.CompleteApp.ViewModels.SupplierViewModel

<div style="padding-top: 20px">
    <div>
        <hr />
        <h4>Endereço</h4>
    </div>

    @if (Model != null)
    {
        <vc:summary></vc:summary>
        <table class="table table-hover">
            <thead class="thead-dark">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Address.Street)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Address.Number)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Address.Complement)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Address.ZipCode)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Address.Neighborhood)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Address.City)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Address.State)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => modelItem.Address.Street)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => modelItem.Address.Number)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => modelItem.Address.Complement)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => modelItem.Address.ZipCode)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => modelItem.Address.Neighborhood)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => modelItem.Address.City)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => modelItem.Address.State)
                    </td>
                    <td>
                        <a asp-action="UpdateAddress" supress-by-action="Edit,GetAddress" asp-route-id="@Model.Id" class="btn btn-info" data-modal="">
                            <span title="Editar" class="fa fa-pencil-alt"></span>
                        </a>
                    </td>
                </tr>
            </tbody>
        </table>
    }


</div>

src/RSS.CompleteApp/Views/Supplier/_UpdateAddress.cshtml
@model RSS.CompleteApp.ViewModels.SupplierViewModel

@{ 
    ViewData["Title"] = "Atualizar Endereço";
}

<div class="modal-header">
    <h4 class="modal-title">@ViewData["Title"]</h4>
    <button type="button" class="close" data-dismiss="modal">
        <span aria-hidden="true">x</span>
        <span class="sr-only">Fechar</span>
    </button>
</div>

<form asp-action="UpdateAddress">
    <div class="modal-body">
        <input type="hidden" asp-for="Address.SupplierId" />
        <input type="hidden" asp-for="Address.Id" />

        <partial name="_Address" />
    </div>
    <div class="modal-footer">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Atualizar Endereço" class="btn btn-success" />
            <input type="button" value="Fechar" class="btn btn-info" data-dismiss="modal"/>
        </div>
    </div>
</form>

<script>
    BuscaCep();
</script>